/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.justtrack.hausamsee;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Click extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3755028435642971921L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Click\",\"namespace\":\"io.justtrack.hausamsee\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"storeId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"campaignId\",\"type\":\"int\"},{\"name\":\"geo\",\"type\":{\"type\":\"record\",\"name\":\"Geo\",\"fields\":[{\"name\":\"city\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"countryCode\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}},{\"name\":\"createdAt\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<Click> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Click> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Click> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Click> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Click> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Click to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Click from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Click instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Click fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String id;
  private java.lang.String storeId;
  private int campaignId;
  private io.justtrack.hausamsee.Geo geo;
  private java.time.Instant createdAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Click() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param storeId The new value for storeId
   * @param campaignId The new value for campaignId
   * @param geo The new value for geo
   * @param createdAt The new value for createdAt
   */
  public Click(java.lang.String id, java.lang.String storeId, java.lang.Integer campaignId, io.justtrack.hausamsee.Geo geo, java.time.Instant createdAt) {
    this.id = id;
    this.storeId = storeId;
    this.campaignId = campaignId;
    this.geo = geo;
    this.createdAt = createdAt.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return storeId;
    case 2: return campaignId;
    case 3: return geo;
    case 4: return createdAt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = value$ != null ? value$.toString() : null; break;
    case 1: storeId = value$ != null ? value$.toString() : null; break;
    case 2: campaignId = (java.lang.Integer)value$; break;
    case 3: geo = (io.justtrack.hausamsee.Geo)value$; break;
    case 4: createdAt = (java.time.Instant)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'storeId' field.
   * @return The value of the 'storeId' field.
   */
  public java.lang.String getStoreId() {
    return storeId;
  }


  /**
   * Sets the value of the 'storeId' field.
   * @param value the value to set.
   */
  public void setStoreId(java.lang.String value) {
    this.storeId = value;
  }

  /**
   * Gets the value of the 'campaignId' field.
   * @return The value of the 'campaignId' field.
   */
  public int getCampaignId() {
    return campaignId;
  }


  /**
   * Sets the value of the 'campaignId' field.
   * @param value the value to set.
   */
  public void setCampaignId(int value) {
    this.campaignId = value;
  }

  /**
   * Gets the value of the 'geo' field.
   * @return The value of the 'geo' field.
   */
  public io.justtrack.hausamsee.Geo getGeo() {
    return geo;
  }


  /**
   * Sets the value of the 'geo' field.
   * @param value the value to set.
   */
  public void setGeo(io.justtrack.hausamsee.Geo value) {
    this.geo = value;
  }

  /**
   * Gets the value of the 'createdAt' field.
   * @return The value of the 'createdAt' field.
   */
  public java.time.Instant getCreatedAt() {
    return createdAt;
  }


  /**
   * Sets the value of the 'createdAt' field.
   * @param value the value to set.
   */
  public void setCreatedAt(java.time.Instant value) {
    this.createdAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Creates a new Click RecordBuilder.
   * @return A new Click RecordBuilder
   */
  public static io.justtrack.hausamsee.Click.Builder newBuilder() {
    return new io.justtrack.hausamsee.Click.Builder();
  }

  /**
   * Creates a new Click RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Click RecordBuilder
   */
  public static io.justtrack.hausamsee.Click.Builder newBuilder(io.justtrack.hausamsee.Click.Builder other) {
    if (other == null) {
      return new io.justtrack.hausamsee.Click.Builder();
    } else {
      return new io.justtrack.hausamsee.Click.Builder(other);
    }
  }

  /**
   * Creates a new Click RecordBuilder by copying an existing Click instance.
   * @param other The existing instance to copy.
   * @return A new Click RecordBuilder
   */
  public static io.justtrack.hausamsee.Click.Builder newBuilder(io.justtrack.hausamsee.Click other) {
    if (other == null) {
      return new io.justtrack.hausamsee.Click.Builder();
    } else {
      return new io.justtrack.hausamsee.Click.Builder(other);
    }
  }

  /**
   * RecordBuilder for Click instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Click>
    implements org.apache.avro.data.RecordBuilder<Click> {

    private java.lang.String id;
    private java.lang.String storeId;
    private int campaignId;
    private io.justtrack.hausamsee.Geo geo;
    private io.justtrack.hausamsee.Geo.Builder geoBuilder;
    private java.time.Instant createdAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.justtrack.hausamsee.Click.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.storeId)) {
        this.storeId = data().deepCopy(fields()[1].schema(), other.storeId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.campaignId)) {
        this.campaignId = data().deepCopy(fields()[2].schema(), other.campaignId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.geo)) {
        this.geo = data().deepCopy(fields()[3].schema(), other.geo);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (other.hasGeoBuilder()) {
        this.geoBuilder = io.justtrack.hausamsee.Geo.newBuilder(other.getGeoBuilder());
      }
      if (isValidValue(fields()[4], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[4].schema(), other.createdAt);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing Click instance
     * @param other The existing instance to copy.
     */
    private Builder(io.justtrack.hausamsee.Click other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.storeId)) {
        this.storeId = data().deepCopy(fields()[1].schema(), other.storeId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.campaignId)) {
        this.campaignId = data().deepCopy(fields()[2].schema(), other.campaignId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.geo)) {
        this.geo = data().deepCopy(fields()[3].schema(), other.geo);
        fieldSetFlags()[3] = true;
      }
      this.geoBuilder = null;
      if (isValidValue(fields()[4], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[4].schema(), other.createdAt);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.String getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public io.justtrack.hausamsee.Click.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public io.justtrack.hausamsee.Click.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'storeId' field.
      * @return The value.
      */
    public java.lang.String getStoreId() {
      return storeId;
    }


    /**
      * Sets the value of the 'storeId' field.
      * @param value The value of 'storeId'.
      * @return This builder.
      */
    public io.justtrack.hausamsee.Click.Builder setStoreId(java.lang.String value) {
      validate(fields()[1], value);
      this.storeId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'storeId' field has been set.
      * @return True if the 'storeId' field has been set, false otherwise.
      */
    public boolean hasStoreId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'storeId' field.
      * @return This builder.
      */
    public io.justtrack.hausamsee.Click.Builder clearStoreId() {
      storeId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'campaignId' field.
      * @return The value.
      */
    public int getCampaignId() {
      return campaignId;
    }


    /**
      * Sets the value of the 'campaignId' field.
      * @param value The value of 'campaignId'.
      * @return This builder.
      */
    public io.justtrack.hausamsee.Click.Builder setCampaignId(int value) {
      validate(fields()[2], value);
      this.campaignId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'campaignId' field has been set.
      * @return True if the 'campaignId' field has been set, false otherwise.
      */
    public boolean hasCampaignId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'campaignId' field.
      * @return This builder.
      */
    public io.justtrack.hausamsee.Click.Builder clearCampaignId() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'geo' field.
      * @return The value.
      */
    public io.justtrack.hausamsee.Geo getGeo() {
      return geo;
    }


    /**
      * Sets the value of the 'geo' field.
      * @param value The value of 'geo'.
      * @return This builder.
      */
    public io.justtrack.hausamsee.Click.Builder setGeo(io.justtrack.hausamsee.Geo value) {
      validate(fields()[3], value);
      this.geoBuilder = null;
      this.geo = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'geo' field has been set.
      * @return True if the 'geo' field has been set, false otherwise.
      */
    public boolean hasGeo() {
      return fieldSetFlags()[3];
    }

    /**
     * Gets the Builder instance for the 'geo' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public io.justtrack.hausamsee.Geo.Builder getGeoBuilder() {
      if (geoBuilder == null) {
        if (hasGeo()) {
          setGeoBuilder(io.justtrack.hausamsee.Geo.newBuilder(geo));
        } else {
          setGeoBuilder(io.justtrack.hausamsee.Geo.newBuilder());
        }
      }
      return geoBuilder;
    }

    /**
     * Sets the Builder instance for the 'geo' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public io.justtrack.hausamsee.Click.Builder setGeoBuilder(io.justtrack.hausamsee.Geo.Builder value) {
      clearGeo();
      geoBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'geo' field has an active Builder instance
     * @return True if the 'geo' field has an active Builder instance
     */
    public boolean hasGeoBuilder() {
      return geoBuilder != null;
    }

    /**
      * Clears the value of the 'geo' field.
      * @return This builder.
      */
    public io.justtrack.hausamsee.Click.Builder clearGeo() {
      geo = null;
      geoBuilder = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdAt' field.
      * @return The value.
      */
    public java.time.Instant getCreatedAt() {
      return createdAt;
    }


    /**
      * Sets the value of the 'createdAt' field.
      * @param value The value of 'createdAt'.
      * @return This builder.
      */
    public io.justtrack.hausamsee.Click.Builder setCreatedAt(java.time.Instant value) {
      validate(fields()[4], value);
      this.createdAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'createdAt' field has been set.
      * @return True if the 'createdAt' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'createdAt' field.
      * @return This builder.
      */
    public io.justtrack.hausamsee.Click.Builder clearCreatedAt() {
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Click build() {
      try {
        Click record = new Click();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.storeId = fieldSetFlags()[1] ? this.storeId : (java.lang.String) defaultValue(fields()[1]);
        record.campaignId = fieldSetFlags()[2] ? this.campaignId : (java.lang.Integer) defaultValue(fields()[2]);
        if (geoBuilder != null) {
          try {
            record.geo = this.geoBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("geo"));
            throw e;
          }
        } else {
          record.geo = fieldSetFlags()[3] ? this.geo : (io.justtrack.hausamsee.Geo) defaultValue(fields()[3]);
        }
        record.createdAt = fieldSetFlags()[4] ? this.createdAt : (java.time.Instant) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Click>
    WRITER$ = (org.apache.avro.io.DatumWriter<Click>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Click>
    READER$ = (org.apache.avro.io.DatumReader<Click>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










